POST https://localhost:3000/api/v1/users/register/
Content-Type: application/json

{"username": "tom", "email": "tom@mail.com", "password": "Test123*", "confirm_password": "Test123*"}

###


GET https://localhost:3000/api/v1/users/accounts/
Content-Type: application/json

{}

###

GET https://localhost:3000/api/v1/users/accounts/1
Content-Type: application/json

{}

###

GET https://localhost:3000/api/v1/users/accounts/1
Content-Type: application/json
Authorization: Bearer <token>

{}
