# Generated by Django 5.1.2 on 2025-02-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salon',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mail', models.CharField()),
                ('password', models.CharField()),
                ('mode', models.CharField(choices=[('Offline', 'offline'), ('Online', 'online')], default='Offline')),
                ('play', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('2P', 'soloq'), ('4P', 'tournament')])),
                ('salon', models.ManyToManyField(blank=True, to='Selectmode.salon')),
            ],
            options={
                'db_table': 'mode',
            },
        ),
        migrations.AddField(
            model_name='salon',
            name='player',
            field=models.ManyToManyField(blank=True, to='Selectmode.user'),
        ),
        migrations.AddField(
            model_name='salon',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_left', to='Selectmode.user'),
        ),
        migrations.AddField(
            model_name='salon',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_right', to='Selectmode.user'),
        ),
    ]
