# Generated by Django 5.1 on 2024-10-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selectmode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='salon',
            field=models.ManyToManyField(blank=True, to='Selectmode.salon'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='player',
            field=models.ManyToManyField(blank=True, to='Selectmode.user'),
        ),
    ]
