# Generated by Django 5.1 on 2024-10-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selectmode', '0002_alter_mode_salon_alter_salon_player'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mode',
            table='Mode',
        ),
        migrations.AlterModelTable(
            name='salon',
            table='Salon',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
