# Generated by Django 5.1 on 2024-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('mail', models.IntegerField()),
                ('password', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='transcendance',
        ),
    ]
