# Generated by Django 4.2 on 2024-12-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blockeduser',
            table='blocked_users',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
