# Generated by Django 5.1.2 on 2025-02-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tournament_game'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='Game',
        ),
        migrations.AlterModelTable(
            name='tournament',
            table='Tournament',
        ),
    ]
