# COMMENTER CE CODE SI CHANGEMENT, NE PAS SUPPRIMER SVP
FROM django-base

WORKDIR /code

# RUN pip install --upgrade pip

# COPY requirements.txt .

# RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["./start.sh"]

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]