POST http://localhost:9090/api/auth/signup
Content-Type: application/json

{ "username": "test1", "email": "test1@gmail.fr", "password": "test1" }

###

POST http://127.0.0.1:9090/api/auth/login
Content-Type: application/json

{ "email": "test1@mail.fr", "password": "test1", "otp": "775245" }

###

POST http://127.0.0.1:9090/api/auth/2fa/enable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzMzMTUwNzE1LCJpYXQiOjE3MzMxNDcxMTV9.CS1seiMasxRfzKcrN7CuEpCbJDL768MNq7LdybSRqKZRVgIcvblTeb8r2ahktaPSA4l0rogsznMYkDPgc0_jB1A71cnJZFUnY4gBy-paRTJSjE7toxU2pnhLHYk9M3nzjeO6nVHyfxHfpF5Q4DCQIsCWPht7NgWLfpjfYbpE7TPZ_bTIw98E-y3vH2LUbaNUHpoY51Qu75Cpi3UJP_CVknYxbpaBE49rej1m2Lg4koL2gtgf6itZN3MqzIZR0tF_Wla9s1uuP59dEerIdNhZguTOS1d_mb8Oxm-zPSlI_pxfsnedwjuXngwrBYky20hViAFjTquXUQFWBSK4Y7UCig

{}

###

POST http://127.0.0.1:9090/api/auth/2fa/disable-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzMzMTUwNzE1LCJpYXQiOjE3MzMxNDcxMTV9.CS1seiMasxRfzKcrN7CuEpCbJDL768MNq7LdybSRqKZRVgIcvblTeb8r2ahktaPSA4l0rogsznMYkDPgc0_jB1A71cnJZFUnY4gBy-paRTJSjE7toxU2pnhLHYk9M3nzjeO6nVHyfxHfpF5Q4DCQIsCWPht7NgWLfpjfYbpE7TPZ_bTIw98E-y3vH2LUbaNUHpoY51Qu75Cpi3UJP_CVknYxbpaBE49rej1m2Lg4koL2gtgf6itZN3MqzIZR0tF_Wla9s1uuP59dEerIdNhZguTOS1d_mb8Oxm-zPSlI_pxfsnedwjuXngwrBYky20hViAFjTquXUQFWBSK4Y7UCig
