POST https://localhost:3000/api/v1/auth/login
Content-Type: application/json

{"email": "tom@mail.com", "password": "Test123*"}

###

POST https://localhost:3000/api/v1/auth/refresh
Content-Type: application/json

{"email": "tom@mail.com"}

###

POST https://localhost:3000/api/v1/auth/logout
Content-Type: application/json

{}
