POST https://localhost:3000/api/v1/auth/login
Content-Type: application/json

{"email": "bob@mail.com", "password": "Test123*"}

###

POST https://localhost:3000/api/v1/auth/login
Content-Type: application/json

{"email": "bob@mail.com", "password": "Test123*", "totp": "1234"}

###

POST https://localhost:3000/api/v1/auth/refresh
Content-Type: application/json

{"email": "bob@mail.com"}

###

POST https://localhost:3000/api/v1/auth/logout
Content-Type: application/json

{}

###

POST https://localhost:3000/api/v1/auth/2fa/enable-2fa
Content-Type: application/json
Authorization: Bearer <token>

{}

###

POST https://localhost:3000/api/v1/auth/2fa/disable-2fa
Content-Type: application/json
Authorization: Bearer <token>

{}

