POST https://localhost:3000/api/auth/signup
Content-Type: application/json

{"username": "tom", "email": "tom@mail.fr", "password": "tom"}

###

POST https://localhost:3000/api/auth/login
Content-Type: application/json

{"email": "tom@mail.fr", "password": "tom"}

###

POST https://localhost:3000/api/auth/refresh
Content-Type: application/json

{"email": "tom@mail.fr"}

###

GET https://localhost:3000/api/auth/ping
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzMzMTQ2OTA4LCJpYXQiOjE3MzMxNDY4NDh9.cJTU4yF8gc-DvIwvJIJQxHCINbZPV0suKsBidrURPpzHe0wKGroX3TTFBBCIUJQJL4J_Tq5JCItA3g6Bs1V2FEb_l7yoPtaXpvsYCdKHp3vQ8dCMSoOewHTb2ZeGojoW-6mY1BJiysi4GVpv-3xuqBrVX5H9mdHRL9d38I6EeX9dHNDe6ipkvWuzQKYv5sDDqxUY3_82QvvoQHzixFyQPCBphKNgL4QHgSlArbMmDzsRb-aEymEKaMTBDcYbq9EllZDPE3sqibWHB9D1AycXsYTZlvnpgbwLjWKHvAyiZBVizETvDSNyTsJMKrtzC79YKimyfNMEUrxPtMhhH4Xv2Q

{}

###

POST https://localhost:3000/api/auth/logout
Content-Type: application/json

{}
