services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx
    depends_on:
      - apitest
      - pong
    ports:
      - "3000:443"
    volumes:
      - ./frontend:/usr/share/nginx/frontend
    networks:
      - nginx-network

  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/posgresql/data
    environment:
      POSTGRES_DB: transcendance
      POSTGRES_USER: toto
      POSTGRES_PASSWORD: test
    networks:
      - db-network

  apitest:
    container_name: apitest
    build:
      context: django
      dockerfile: Dockerfile
    volumes:
      - ./django/code/api:/code
    depends_on:
      - postgres
    expose:
      - "8000"
    networks:
      - nginx-network
      - db-network

  pong:
    container_name: pong
    build:
      context: pong
      dockerfile: Dockerfile
    volumes:
      - ./pong/:/code
    depends_on:
      - postgres
    expose:
      - "8006"
    networks:
      - nginx-network
      - db-network


volumes:
  postgres_data:

networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge