
services:
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - pong
      - apitest
    ports:
      - "3000:443"
    volumes:
      - ./frontend:/usr/share/nginx/frontend
    networks:
      - nginx-network

  postgres:
    container_name: posgresql
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/posgresql/data
    environment:
      POSTGRES_DB: transcendance
      POSTGRES_USER: toto
      POSTGRES_PASSWORD: test
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d transcendance -U toto"]
      interval: 3s
      timeout: 2s
      retries: 5

  redis:
    container_name: redis
    image: redis
    expose:
      - 6379
    networks:
      - redis-network
    
  pong:
    container_name: pong
    build:
      context: _Pong
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1  # Désactiver le buffering des sorties Python
    volumes:
      - ./_Pong/:/code
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    expose:
      - "8006"

  apitest:
    container_name: apitest
    build:
      context: matchmaking
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: matchmaking.settings
    volumes:
      - ./matchmaking:/code
    depends_on:
      - postgres
    expose:
      - "8000:8000"
    networks:
      - nginx-network
      - db-network
      - redis-network

volumes:
  postgres_data:

networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge
  redis-network:
    driver: bridge