# Generated by Django 5.1.1 on 2024-10-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mescouilles',
        ),
    ]
