# Generated by Django 5.1.1 on 2024-10-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_delete_mescouilles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mode',
            table='Mode',
        ),
        migrations.AlterModelTable(
            name='salon',
            table='Salon',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
