# Generated by Django 5.1.1 on 2024-10-31 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_mode_table_alter_salon_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salon',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
