# Generated by Django 5.1.1 on 2024-10-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_mode_table_alter_salon_table_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mode',
            table='Mode',
        ),
        migrations.AlterModelTable(
            name='salon',
            table='Salon',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
