# Generated by Django 5.1.2 on 2024-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('in_game', 'In Game')], default='offline', max_length=20)),
                ('friends', models.ManyToManyField(blank=True, to='accounts.user')),
            ],
        ),
    ]
